defaults:
- common
- ../materials/ground@material

geom:
  type: mesh
  file: board.obj
  floor_height: 0.0  # z of top of floor
  floor_thickness: 0.005  # z thickness of floor
  floor_scale: ${eval:'${.floor_thickness} / 0.125'}  # 0.125 is the z scale of board.obj
  floor_bottom: ${eval:'${.floor_height} - ${.floor_thickness}'}
  # preprocessing
  offset_pos: (0.0, 0.0, 0.0)
  offset_euler: (0.0, 0.0, 0.0)
  scale: (1.0, 1.0, ${.floor_scale})
  # placement
  pos: (0.0, 0.0, ${.floor_bottom})  # centered at xy=0, z at top = 0
  euler: (0.0, 0.0, 0.0)

surface:
  color: (0.3, 0.3, 0.3, 1.0)
