name: doughnet
channels:
  - pytorch
  - nvidia
  - pyg
  - defaults
  - conda-forge
dependencies:
  - pip
  - python==3.9.0
  - cudatoolkit==11.8.0
  - pytorch==2.0.0
  - pytorch-cuda==11.8.0
  - torchvision==0.15.0
  - pyg==2.5.2
  - pytorch-cluster==1.6.3
  - numpy==1.24.4
  - scipy==1.10.1
  - networkx==3.1
  - matplotlib==3.8.4
  - pillow==9.4.0
  - tqdm==4.66.1
  - hdf5plugin==4.1.3
  - hdf5==1.14.0
  - colorama==0.4.6
  - trimesh==4.4.1
  - pydantic==2.7.4
  - pip:
    - taichi==1.6.0
    - simple-pid==2.0.1
    - open3d==0.18.0
    - pymeshfix==0.16.2
    - hydra-core==1.3.2
    - omegaconf==2.3.0
